baseURL: "https://hhhyx817.github.io/"

defaultContentLanguage : "en"
title: "Yunxin Huang's Homepage"

     
theme: "PaperMod"

params:
  mainSections:
       
  math: true
  ## code
  ShowCodeCopyButtons: true

  ## toc
  showtoc: false
  tocopen: false
  UseHugoToc: false

  ## additional info
  # ShowPostNavLinks: true
  # ShowWordCount: true
  # ShowReadingTime: true

  ## layout
  # ShowBreadCrumbs: true
  hideSummary: true

  ## use chroma for markup
  assets:
    disableHLJS: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1

    - identifier: cv
      name: CV
      url: /cv/
      weight: 10

    - identifier: coursework
      name: Coursework
      url: /coursework/all-courses/
      weight: 20

    - identifier: graduate-thesis
      name: Gaduate Thesis
      url: /graduate-thesis/
      weight: 20

    # - identifier: sustech
    #   name: SUSTech
    #   url: "https://math.sustech.edu.cn/?lang=en"
    #   weight: 99

## use chroma for syntax highlighting
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
